begin;
create temporary table commerce_test_results(name text,passed boolean,detail text);
grant all on commerce_test_results to authenticated;
do $$
declare u uuid:=gen_random_uuid();v uuid:=gen_random_uuid();b uuid:=gen_random_uuid();other uuid:=gen_random_uuid();c uuid:=gen_random_uuid();other_c uuid:=gen_random_uuid();req uuid:=gen_random_uuid();pay_req uuid:=gen_random_uuid();d jsonb;again jsonb;inv uuid;est uuid;converted uuid;blocked boolean;payload jsonb;count_before bigint;
begin
 insert into auth.users(id,email) values(u,'commerce-'||u||'@example.invalid'),(v,'commerce-'||v||'@example.invalid');
 insert into public.businesses(id,name,created_by_user_id) values(b,'Commerce test',u),(other,'Other business',v);
 insert into public.business_members(business_id,user_id,role) values(b,u,'owner'),(other,v,'owner') on conflict do nothing;
 insert into public.customers(id,business_id,first_name) values(c,b,'Test customer'),(other_c,other,'Other customer');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 if (public.get_plan_usage(b)->>'plan')<>'free' then raise exception 'Expected free plan';end if;
 insert into commerce_test_results values('Default plan is Free Basic',true,null);
 payload:=jsonb_build_object('customer_id',c,'items',jsonb_build_array(jsonb_build_object('description','Work','quantity',1,'unit_price',100,'tax_rate',7)));
 d:=public.create_document(b,'invoice',req,payload);inv:=(d->>'id')::uuid;
 if (d->>'tax_amount')::numeric<>7 or (d->>'total')::numeric<>107 then raise exception 'Incorrect percent tax: %',d;end if;
 insert into commerce_test_results values('7 percent of $100 is $7; invoice total $107',true,null);
 again:=public.create_document(b,'invoice',req,payload);
 if again->>'id'<>d->>'id' or (public.get_plan_usage(b)->>'documents_used')::integer<>1 then raise exception 'Retry duplicated invoice or consumed quota';end if;
 insert into commerce_test_results values('Duplicate document request returns original without extra quota',true,null);
 if (public.get_dashboard_metrics(b)->>'outstanding')::numeric<>0 then raise exception 'Draft counted as outstanding';end if;
 insert into commerce_test_results values('Drafts excluded from receivables',true,null);
 blocked:=false;begin perform public.record_manual_payment(b,inv,gen_random_uuid(),10,'cash','');exception when others then blocked:=true;end;if not blocked then raise exception 'Draft accepted payment';end if;
 insert into commerce_test_results values('Payment on draft rejected',true,null);
 update public.invoices set status='sent' where id=inv;
 d:=public.record_manual_payment(b,inv,pay_req,40,'other','Verified test receipt');
 again:=public.record_manual_payment(b,inv,pay_req,40,'other','Verified test receipt');
 if d->>'id'<>again->>'id' then raise exception 'Duplicate payment';end if;
 select to_jsonb(i) into d from public.invoices i where id=inv;
 if d->>'status'<>'partial' or (d->>'balance_due')::numeric<>67 then raise exception 'Partial payment failed: %',d;end if;
 insert into commerce_test_results values('Partial payment updates balance; retry does not double-charge records',true,null);
 blocked:=false;begin perform public.record_manual_payment(b,inv,gen_random_uuid(),68,'cash','');exception when others then blocked:=true;end;if not blocked then raise exception 'Overpayment accepted';end if;
 insert into commerce_test_results values('Overpayment rejected',true,null);
 blocked:=false;begin update public.invoices set total=0 where id=inv;exception when others then blocked:=true;end;if not blocked then raise exception 'Direct total tampering accepted';end if;
 insert into commerce_test_results values('Direct total tampering rejected',true,null);
 blocked:=false;begin update public.invoice_items set unit_price=2 where invoice_id=inv;exception when others then blocked:=true;end;if not blocked then raise exception 'Issued line item changed';end if;
 insert into commerce_test_results values('Issued line items are immutable',true,null);
 perform public.record_manual_payment(b,inv,gen_random_uuid(),67,'cash','');
 if not exists(select 1 from public.invoices where id=inv and status='paid' and balance_due=0) then raise exception 'Final payment did not settle invoice';end if;
 insert into commerce_test_results values('Full payment settles invoice',true,null);
 d:=public.create_document(b,'estimate',gen_random_uuid(),payload);est:=(d->>'id')::uuid;
 blocked:=false;begin perform public.convert_estimate_to_invoice(est);exception when others then blocked:=true;end;if not blocked then raise exception 'Unaccepted estimate converted';end if;
 update public.estimates set status='accepted' where id=est;
 converted:=public.convert_estimate_to_invoice(est);
 if converted<>public.convert_estimate_to_invoice(est) then raise exception 'Conversion duplicated';end if;
 if not exists(select 1 from public.invoices where id=converted and total=107) then raise exception 'Conversion altered total';end if;
 insert into commerce_test_results values('Accepted estimate converts atomically once with matching totals',true,null);
 select count(*) into count_before from public.invoices where business_id=b;
 blocked:=false;begin perform public.create_document(b,'invoice',gen_random_uuid(),jsonb_build_object('customer_id',c,'items',jsonb_build_array(jsonb_build_object('description','Valid','quantity',1,'unit_price',100,'tax_rate',0),jsonb_build_object('description','Invalid','quantity',0,'unit_price',100,'tax_rate',0))));exception when others then blocked:=true;end;
 if not blocked or (select count(*) from public.invoices where business_id=b)<>count_before then raise exception 'Failed creation left orphan invoice';end if;
 insert into commerce_test_results values('Invalid line rolls back whole document and quota',true,null);
 if exists(select 1 from public.customers where id=other_c) then raise exception 'Cross-business customer visible';end if;
 blocked:=false;begin perform public.create_document(b,'invoice',gen_random_uuid(),jsonb_set(payload,'{customer_id}',to_jsonb(other_c)));exception when others then blocked:=true;end;if not blocked then raise exception 'Cross-business customer attached';end if;
 insert into commerce_test_results values('Cross-business reads and relationship injection blocked',true,null);
 blocked:=false;begin insert into private.business_entitlements(business_id,plan) values(b,'pro');exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'Client self-upgrade accepted';end if;
 insert into commerce_test_results values('Client cannot grant itself Pro',true,null);
 blocked:=false;begin insert into public.business_branding(business_id,logo_data_url) values(b,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aP1sAAAAASUVORK5CYII=');exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'Free image upload accepted';end if;
 insert into commerce_test_results values('Free branding upload blocked by RLS',true,null);
 insert into public.business_settings(business_id,payment_links) values(b,'[{"provider":"stripe","url":"https://buy.stripe.com/test_link"},{"provider":"venmo","url":"https://venmo.com/test-business"}]');
 blocked:=false;begin update public.business_settings set payment_links='[{"provider":"stripe","url":"https://buy.stripe.com.evil.example/payment"}]' where business_id=b;exception when check_violation then blocked:=true;end;if not blocked then raise exception 'Lookalike payment hostname accepted';end if;
 insert into commerce_test_results values('Valid provider links accepted; phishing hostname rejected',true,null);
 blocked:=false;begin update public.business_settings set payment_links='[{"provider":"paypal","url":"javascript:alert(1)"}]' where business_id=b;exception when check_violation then blocked:=true;end;if not blocked then raise exception 'Script payment link accepted';end if;
 insert into commerce_test_results values('Script payment URLs rejected',true,null);
 execute 'reset role';
 update private.monthly_usage set documents=100 where business_id=b;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);execute 'set local role authenticated';
 blocked:=false;begin perform public.create_document(b,'invoice',gen_random_uuid(),payload);exception when check_violation then blocked:=true;end;if not blocked then raise exception 'Quota bypassed';end if;
 insert into commerce_test_results values('Free monthly quota enforced in database',true,null);
 execute 'reset role';
 insert into private.business_entitlements(business_id,plan) values(b,'pro');
 update public.businesses set next_invoice_number=10000 where id=b;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'role','authenticated')::text,true);execute 'set local role authenticated';
 d:=public.create_document(b,'invoice',gen_random_uuid(),payload);
 if d->>'invoice_number'<>'INV-10000' then raise exception 'Document number truncated: %',d->>'invoice_number';end if;
 insert into commerce_test_results values('Five-digit invoice numbers are not truncated',true,null);
 insert into public.business_branding(business_id,logo_data_url) values(b,'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aP1sAAAAASUVORK5CYII=');
 insert into commerce_test_results values('Paid owner can save bounded branding',true,null);
 execute 'reset role';
end$$;
select jsonb_build_object('database','Owedly-Test','fixture_handling','all test rows rolled back','tests',jsonb_agg(to_jsonb(commerce_test_results))) as verification from commerce_test_results;
rollback;
