import {useEffect,useMemo,useRef,useState,type FormEvent} from 'react'
import {canWrite,type CurrentBusiness} from '../lib/business'
import {supabase} from '../lib/supabase'
import {calculateLines,customerName,dateLabel,errorMessage,localDate,money,providerNames,type LineInput,type PaymentLink} from '../lib/commerce'
import {useWorkspace} from '../components/WorkspaceContext'
import {updateDraft,changeDocumentStatus,createDocument,documentHtml,downloadText,getDocument,listDocuments,printDocument,setInvoicePaymentOptions,type DocumentDetail,type DocumentRow,type Kind} from '../services/documents'
import {convertEstimateToInvoice} from '../services/estimates'
import {recordPayment} from '../services/payments'
import InvoicePaymentOptions from '../components/InvoicePaymentOptions'
import InvoiceEmailButton from '../components/InvoiceEmailButton'
import {sendDocumentEmail} from '../services/communications'
import {createApprovalLink} from '../services/approvals'
const blank=():LineInput=>({description:'',quantity:'1',unit_price:'',tax_rate:'0'})
export default function DocumentsPage({business,kind,onNavigate,initialId}:{business:CurrentBusiness;kind:Kind;onNavigate?:(view:string,id?:string)=>void;initialId?:string}){
 const {workspace,refresh:refreshWorkspace}=useWorkspace(),pro=workspace.plan.plan==='pro',writer=canWrite(business.role)
 const [rows,setRows]=useState<DocumentRow[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const [detail,setDetail]=useState<DocumentDetail|null>(null),[selected,setSelected]=useState<string|null>(initialId||null),[showForm,setShowForm]=useState(false),[customers,setCustomers]=useState<any[]>([])
 const [customer,setCustomer]=useState(''),[date,setDate]=useState(''),[message,setMessage]=useState(''),[notes,setNotes]=useState(''),[lines,setLines]=useState<LineInput[]>([blank()])
 const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[amount,setAmount]=useState(''),[method,setMethod]=useState<'cash'|'check'|'card'|'ach'|'other'>('other'),[paymentNote,setPaymentNote]=useState(''),[showPayment,setShowPayment]=useState(false),[verified,setVerified]=useState(false)
 const [editing,setEditing]=useState<DocumentDetail|null>(null),[showReminder,setShowReminder]=useState(false),[reminderAt,setReminderAt]=useState('')
 const requestId=useRef(crypto.randomUUID()),paymentRequest=useRef(crypto.randomUUID())
 const label=kind==='invoice'?'Invoice':'Estimate',limitReached=workspace.plan.documents_used>=workspace.plan.documents_limit||workspace.plan.stored_documents>=workspace.plan.stored_limit
 const preview=useMemo(()=>{try{return {value:calculateLines(lines),error:''}}catch(e){return {value:null,error:errorMessage(e)}}},[lines])
 const currency=workspace.profile.currency
 async function load(){setLoading(true);try{if(selected)setDetail(await getDocument(business.id,kind,selected));else {const result=await listDocuments(business.id,kind,page);setRows(result.rows);setTotal(result.count)}setError('')}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{let active=true;setLoading(true);setError('');const promise=selected?getDocument(business.id,kind,selected):listDocuments(business.id,kind,page);promise.then(result=>{if(!active)return;if('document' in result)setDetail(result);else{setRows(result.rows);setTotal(result.count)}}).catch(e=>{if(active)setError(errorMessage(e))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[business.id,kind,selected,page])
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(showForm){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',handler);window.dispatchEvent(new CustomEvent('owedly:dirty',{detail:showForm}));return()=>{window.removeEventListener('beforeunload',handler);window.dispatchEvent(new CustomEvent('owedly:dirty',{detail:false}))}},[showForm])
 async function action(task:()=>Promise<unknown>,success?:string){setBusy(true);setError('');setNotice('');try{await task();if(success)setNotice(success);await refreshWorkspace();await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function openForm(source?:DocumentDetail,edit=false){
  setEditing(edit&&source?source:null)
  setBusy(true);setError('');try{const all:any[]=[];for(let offset=0;;offset+=500){const {data,error}=await supabase.from('customers').select('id,first_name,last_name,company,email').eq('business_id',business.id).eq('archived',false).order('created_at').range(offset,offset+499);if(error)throw error;all.push(...data);if(data.length<500)break}setCustomers(all);if(!all.length){setNotice('Add a customer first, then create your document.');onNavigate?.('customers');return}
   setCustomer(source?.document.customer_id||'');setDate(edit?(source?.document.due_date||source?.document.expires_on||''):'');setMessage(source?.document.customer_message||'');setNotes(source?.document.notes||'');setLines(source?source.items.map(i=>({description:i.description,quantity:String(i.quantity),unit_price:String(i.unit_price),tax_rate:String(i.tax_rate||0)})):[blank()]);requestId.current=crypto.randomUUID();setShowForm(true)
  }catch(e){setError(errorMessage(e))}finally{setBusy(false)}
 }
 async function submit(event:FormEvent){event.preventDefault();if(!preview.value||!customer)return;setBusy(true);setError('');try{const input={customer_id:customer,...(kind==='invoice'?{due_date:date}:{expires_on:date}),customer_message:message,notes,items:lines};const created=editing?await updateDraft(business.id,kind,editing.document.id,editing.document.updated_at,input):await createDocument(business.id,kind,requestId.current,input);setShowForm(false);setSelected(created.id);setDetail(await getDocument(business.id,kind,created.id));await refreshWorkspace();setNotice(`${label} ${editing?'updated':'created'}. Review it before sharing.`)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function setDocumentStatus(next:string){if(!detail)return;const explanation=next==='accepted'||next==='declined'?`Record the customer's ${next==='accepted'?'acceptance':'decline'} of this estimate? Use this only after they have told you their decision. This does not create an electronic signature.`:next==='void'?'Void this invoice? This is permanent and does not refund money.':`Mark this ${label.toLowerCase()} as sent? This records that you shared it outside Owedly; no email will be sent.`;if(!window.confirm(explanation))return;await action(()=>changeDocumentStatus(business.id,kind,detail.document.id,next),'Status updated.')}
 async function convert(){if(!detail||!window.confirm('Create one draft invoice from this accepted estimate? This uses one document from your monthly allowance.'))return;setBusy(true);setError('');try{const id=await convertEstimateToInvoice(detail.document.id);await refreshWorkspace();onNavigate?.('invoices',id)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function emailEstimate(){if(!detail||!window.confirm(`Send this estimate to ${Array.isArray(detail.document.customers)?detail.document.customers[0]?.email:detail.document.customers?.email}?`))return;await action(()=>sendDocumentEmail(business.id,'estimate',detail.document.id),'Email accepted by the sending service. Inbox delivery may still fail.')}
 async function shareApproval(){if(!detail)return;await action(async()=>{const link=await createApprovalLink(business.id,'estimate',detail.document.id);await navigator.clipboard.writeText(link.url)},'Approval link copied. Share it only with the intended customer.')}
 async function savePayment(e:FormEvent){e.preventDefault();if(!detail||!verified)return;await action(async()=>{await recordPayment(business.id,{invoice_id:detail.document.id,amount:Number(amount),method,notes:paymentNote,request_id:paymentRequest.current});setShowPayment(false)},'Payment recorded. This does not charge or refund a payment account.')}
 const filtered=rows.filter(r=>(status==='all'||r.status===status)&&`${r.invoice_number||r.estimate_number} ${customerName(r.customers)}`.toLowerCase().includes(search.toLowerCase()))
 const doc=detail?.document
 return <div className="page-stack documents-page">
 <div className="page-heading split-heading"><div><p className="eyebrow">{kind==='invoice'?'Get paid':'Win the work'}</p><h1>{selected?(doc?.invoice_number||doc?.estimate_number||label):`${label}s`}</h1><p className="quiet">{selected?'Review, share, and track — without guesswork.':`${Math.max(0,workspace.plan.documents_limit-workspace.plan.documents_used)} new documents left this month.`}</p></div>{writer&&!selected&&<button className="primary-button" disabled={busy||limitReached} onClick={()=>openForm()}>+ New {kind}</button>}</div>
 {error&&<div className="banner error-text" role="alert">{error} <button className="text-button" onClick={load}>Retry loading</button></div>}{notice&&<p className="banner success-text" role="status">{notice}</p>}
 {selected&&<button className="back-button" onClick={()=>{setSelected(null);setDetail(null);setNotice('')}}>← All {kind}s</button>}
 {loading?<div role="status" className="detail-card">Loading {kind}s…</div>:selected&&doc&&detail?<>
 <div className="document-toolbar">
 <button className="secondary-button" disabled={busy} onClick={()=>action(()=>printDocument(documentHtml(detail,workspace)))}>Print / Save PDF</button>
 <button className="secondary-button" disabled={busy} onClick={()=>downloadText(`${doc.invoice_number||doc.estimate_number}.html`,documentHtml(detail,workspace),'text/html')}>Download document</button>
 {writer&&<button className="secondary-button" disabled={busy||limitReached} onClick={()=>openForm(detail)}>Duplicate as new draft</button>}
 {writer&&doc.status==='draft'&&<button className="secondary-button" disabled={busy} onClick={()=>openForm(detail,true)}>Edit draft</button>}
 {writer&&doc.status==='draft'&&<button className="secondary-button" disabled={busy} onClick={()=>setDocumentStatus('sent')}>Mark shared manually</button>}
 {writer&&pro&&kind==='invoice'&&doc.status!=='void'&&<InvoiceEmailButton businessId={business.id} invoiceId={doc.id} recipient={(Array.isArray(doc.customers)?doc.customers[0]:doc.customers)?.email||null} onSent={async()=>{setDetail(await getDocument(business.id,kind,doc.id));await refreshWorkspace();setNotice('Email accepted by the sending service. This is not a guarantee of inbox delivery.')}}/>}
 {writer&&pro&&kind==='estimate'&&!['accepted','declined','converted','expired'].includes(doc.status)&&<button className="primary-button" disabled={busy} onClick={emailEstimate}>Email customer</button>}
 {writer&&kind==='estimate'&&!['accepted','declined','converted','expired'].includes(doc.status)&&<><button className="secondary-button" disabled={busy} onClick={()=>setDocumentStatus('accepted')}>Record acceptance</button><button className="secondary-button" disabled={busy} onClick={()=>setDocumentStatus('declined')}>Record decline</button>{pro&&<button className="secondary-button" disabled={busy} onClick={shareApproval}>Copy approval link</button>}</>}
 {writer&&kind==='estimate'&&doc.status==='accepted'&&<button className="primary-button" disabled={busy||limitReached} onClick={convert}>Create invoice</button>}
 {writer&&kind==='invoice'&&!['draft','void','paid'].includes(doc.status)&&<button className="secondary-button" onClick={()=>{setReminderAt('');setShowReminder(true)}}>Schedule follow-up</button>}
 {writer&&kind==='invoice'&&!['draft','void','paid'].includes(doc.status)&&Number(doc.balance_due)>0&&<button className="primary-button" disabled={busy} onClick={()=>{setAmount(String(doc.balance_due));setVerified(false);setPaymentNote('');paymentRequest.current=crypto.randomUUID();setShowPayment(true)}}>Record payment received</button>}
 </div>
 {!pro&&<p className="banner">Free Basic: download or save a PDF, then send it with your own email or messaging app. Owedly does not send an email when you download or mark a document shared.</p>}
 <iframe className="document-preview" title={`${label} preview`} srcDoc={documentHtml(detail,workspace)} sandbox="allow-popups allow-popups-to-escape-sandbox"/>
 {kind==='invoice'&&doc.status==='draft'&&['owner','admin'].includes(business.role)&&<details className="detail-card"><summary>Payment options for this invoice</summary><InvoicePaymentOptions key={doc.id+doc.updated_at} businessId={business.id} invoiceId={doc.id} links={doc.payment_links||[]} instructions={doc.payment_instructions||''} onSaved={async()=>{setDetail(await getDocument(business.id,kind,doc.id));setNotice('Invoice payment options saved.')}}/><p>New invoices copy the business defaults. Refresh this draft after changing Settings, or leave the original options intact. Verify any fixed-amount provider link matches this invoice.</p><button className="secondary-button" disabled={busy} onClick={()=>action(()=>setInvoicePaymentOptions(business.id,doc.id,workspace.payment_links,workspace.payment_instructions),'Payment settings copied into this draft.')}>Use current business payment options</button><button className="text-button" onClick={()=>onNavigate?.('settings')}>Manage business payment options</button></details>}
 <details className="detail-card"><summary>Internal notes & payment history</summary><p className="quiet">Internal notes never appear on the customer-facing preview, download, or email.</p><p>{doc.notes||'No internal notes.'}</p>{detail.payments.map(p=><div className="history-row" key={p.id}><span>{dateLabel(p.paid_at)} · {p.method} · {p.status}</span><strong>{money(p.amount,currency)}</strong></div>)}</details>
 {writer&&kind==='invoice'&&doc.status!=='void'&&Number(doc.amount_paid||0)===0&&<button className="text-button danger-button" disabled={busy} onClick={()=>setDocumentStatus('void')}>Void invoice</button>}
 </>:!selected?<>
 <div className="filter-bar"><label>Filter this page<input type="search" placeholder="Document number or customer" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{(kind==='invoice'?['draft','sent','viewed','partial','paid','overdue','void']:['draft','sent','accepted','declined','expired','converted']).map(s=><option key={s}>{s}</option>)}</select></label></div>
 <section className="list-card">{filtered.length?filtered.map(r=><button className="document-list-button" key={r.id} onClick={()=>{setSelected(r.id);setDetail(null);setNotice('')}}><div><strong>{r.invoice_number||r.estimate_number}</strong><span>{customerName(r.customers)} · {dateLabel(r.issue_date)}</span></div><span className="status-chip">{r.status}</span><div><strong>{money(r.total,currency)}</strong>{kind==='invoice'&&<small>{money(r.balance_due||0,currency)} remaining</small>}</div></button>):<div className="empty-state"><h2>{error?'Documents unavailable':rows.length?'No matches on this page':`No ${kind}s yet`}</h2><p>{rows.length?'Try a different filter or page.':`Add a customer, create an ${kind}, then review before sharing.`}</p>{writer&&!rows.length&&<button className="primary-button" disabled={busy||limitReached} onClick={()=>openForm()}>Create {kind}</button>}</div>}</section>
 <div className="pagination"><button disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{total} documents · Page {page+1} of {Math.max(1,Math.ceil(total/50))}</span><button disabled={(page+1)*50>=total||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div>
 </>:null}
 {showReminder&&doc&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="reminder-title"><h2 id="reminder-title">Schedule an in-app follow-up</h2><form onSubmit={e=>{e.preventDefault();action(async()=>{const due=new Date(reminderAt);if(!Number.isFinite(due.getTime())||due.getTime()<=Date.now())throw new Error('Choose a future time.');const {error}=await supabase.from('reminders').insert({business_id:business.id,invoice_id:doc.id,customer_id:doc.customer_id,kind:'invoice_follow_up',due_at:due.toISOString(),status:'pending',note:`Follow up on ${doc.invoice_number}`});if(error)throw error;setShowReminder(false)},'Follow-up scheduled in your dashboard.')}}><label>Reminder time (your device timezone)<input type="datetime-local" required value={reminderAt} onChange={e=>setReminderAt(e.target.value)}/></label><p>This appears in your dashboard. No automated email or phone notification is sent.</p>{error&&<p role="alert" className="error-text">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>setShowReminder(false)}>Cancel</button><button className="primary-button" disabled={busy}>Save follow-up</button></div></form></section></div>}
 {showForm&&<div className="modal-backdrop"><section className="modal wide" role="dialog" aria-modal="true" aria-labelledby="document-form-title"><div className="modal-head"><h2 id="document-form-title">{editing?'Edit':'New'} {kind}</h2><button className="icon-button" aria-label="Close document form" disabled={busy} onClick={()=>{if(window.confirm('Discard this unsaved draft?'))setShowForm(false)}}>×</button></div><form className="estimate-form" onSubmit={submit}><div className="form-grid"><label className="full">Customer<select required value={customer} onChange={e=>setCustomer(e.target.value)} disabled={busy}><option value="">Choose customer…</option>{customers.map(c=><option key={c.id} value={c.id}>{customerName(c)}</option>)}</select></label><label>{kind==='invoice'?'Due date':'Valid through'}<input type="date" min={localDate(workspace.profile.timezone)} value={date} onChange={e=>setDate(e.target.value)} disabled={busy}/></label></div>
 <div className="line-items"><div className="line-items-head"><strong>Line items</strong><button type="button" className="text-button" disabled={busy||lines.length>=50} onClick={()=>setLines([...lines,blank()])}>+ Add line</button></div>{lines.map((line,index)=><div className="line-item" key={index}><input aria-label={`Description ${index+1}`} placeholder="Description" maxLength={1000} value={line.description} disabled={busy} required onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,description:e.target.value}:l))}/>{(['quantity','unit_price','tax_rate'] as const).map(field=><input key={field} aria-label={`${field==='quantity'?'Quantity':field==='unit_price'?'Unit price':'Tax percent'} ${index+1}`} type="number" step="0.01" min={field==='quantity'?'0.01':'0'} max={field==='tax_rate'?'100':field==='quantity'?'100000':'10000000'} value={line[field]} disabled={busy} required onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,[field]:e.target.value}:l))}/>)}<button type="button" className="remove-line" aria-label={`Remove line ${index+1}`} disabled={busy||lines.length===1} onClick={()=>setLines(lines.filter((_,i)=>i!==index))}>×</button></div>)}</div>
 <p className="quiet">Columns: description, quantity, unit price, tax %. Enter 7 for 7% tax. Each line and its tax are rounded to cents.</p>
 <div className="estimate-total"><span>Subtotal {money(preview.value?.subtotal||0,currency)} · Tax {money(preview.value?.tax_amount||0,currency)}</span><strong>Total {money(preview.value?.total||0,currency)}</strong></div>
 <label>Message to customer<textarea value={message} maxLength={4000} onChange={e=>setMessage(e.target.value)} disabled={busy}/></label><label>Internal notes — never shared<textarea value={notes} maxLength={4000} onChange={e=>setNotes(e.target.value)} disabled={busy}/></label>
 {error&&<p role="alert" className="error-text">{error}</p>}<div className="modal-actions"><button className="secondary-button" type="button" disabled={busy} onClick={()=>{if(window.confirm('Discard this unsaved draft?'))setShowForm(false)}}>Cancel</button><button className="primary-button" disabled={busy||!preview.value||!customer}>{busy?'Saving…':editing?'Save draft':`Create ${kind}`}</button></div></form></section></div>}
 {showPayment&&detail&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="payment-title"><h2 id="payment-title">Record money already received</h2><form className="form-grid" onSubmit={savePayment}><label>Amount<input type="number" min="0.01" step="0.01" max={Number(doc?.balance_due)} value={amount} required disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><label>Method<select value={method} disabled={busy} onChange={e=>setMethod(e.target.value as typeof method)}><option value="other">Venmo / PayPal / other</option><option value="cash">Cash</option><option value="check">Check</option><option value="card">Card</option><option value="ach">Bank transfer / ACH</option></select></label><label className="full">Receipt or transaction reference<input value={paymentNote} maxLength={2000} onChange={e=>setPaymentNote(e.target.value)} disabled={busy}/></label><label className="full checkbox-label"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)} disabled={busy} required/>I verified the payment in my provider account or received the money. This only updates Owedly’s records.</label>{error&&<p className="full error-text" role="alert">{error}</p>}<div className="full modal-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>setShowPayment(false)}>Cancel</button><button className="primary-button" disabled={busy||!verified}>{busy?'Recording…':'Record verified payment'}</button></div></form></section></div>}
 </div>
}
