import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
import type {CurrentBusiness} from '../lib/business'
import {money,errorMessage,dateLabel,customerName} from '../lib/commerce'
import {useWorkspace} from '../components/WorkspaceContext'
export default function PaymentsPage({business,onNavigate}:{business:CurrentBusiness;onNavigate?:(view:string,id?:string)=>void}){
 const {workspace}=useWorkspace(),[rows,setRows]=useState<any[]>([]),[page,setPage]=useState(0),[count,setCount]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 async function load(){setLoading(true);setError('');try{const {data,error,count}=await supabase.from('payments').select('id,invoice_id,amount,method,provider,status,paid_at,notes,invoices:invoices!payments_invoice_id_fkey(invoice_number,customers:customers!invoices_customer_id_fkey(first_name,last_name,company))',{count:'exact'}).eq('business_id',business.id).order('paid_at',{ascending:false}).range(page*50,page*50+49);if(error)throw error;setRows(data||[]);setCount(count||0)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[business.id,page])
 return <div className="page-stack"><div className="page-heading split-heading"><div><p className="eyebrow">Payments</p><h1>Know what has been recorded.</h1></div><button className="primary-button" onClick={()=>onNavigate?.('invoices')}>Record payment on an invoice</button></div><p className="banner">These are your business’s payment records, not a live bank feed. Verify receipt in Stripe, Venmo, PayPal, or your bank before recording money. Amounts shown are before payment-provider fees.</p>{error&&<p className="banner error-text" role="alert">{error}<button onClick={load}>Retry</button></p>}{loading?<p role="status">Loading payments…</p>:<section className="list-card">{rows.length?rows.map(p=>{const inv=Array.isArray(p.invoices)?p.invoices[0]:p.invoices;return <button className="document-list-button" key={p.id} onClick={()=>onNavigate?.('invoices',p.invoice_id)}><div><strong>{inv?.invoice_number||'Invoice'} · {customerName(inv?.customers)}</strong><span>{dateLabel(p.paid_at)} · {p.method||'Other'} · {p.status}</span></div><strong>{money(p.amount,workspace.profile.currency)}</strong></button>}):<div className="empty-state"><h2>{error?'Payments unavailable':'No payments recorded yet'}</h2><p>Open an issued invoice to record a verified payment.</p></div>}</section>}<div className="pagination"><button disabled={!page||loading} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{count} payments · Page {page+1}</span><button disabled={(page+1)*50>=count||loading} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>
}
