import {useState,type FormEvent} from 'react'
import type {CurrentBusiness} from '../lib/business'
import {errorMessage,providerNames,validatePaymentLinks,type PaymentLink,type PaymentProvider} from '../lib/commerce'
import {useWorkspace} from '../components/WorkspaceContext'
import {prepareLogo,saveLogo,savePaymentSettings,saveProfile} from '../services/workspace'
import {exportWorkspace} from '../services/documents'
export default function SettingsPage({business}:{business:CurrentBusiness}){
 const {workspace,refresh}=useWorkspace()
 const [profile,setProfile]=useState(workspace.profile),[links,setLinks]=useState<PaymentLink[]>(workspace.payment_links),[instructions,setInstructions]=useState(workspace.payment_instructions)
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const admin=['owner','admin'].includes(business.role), pro=workspace.plan.plan==='pro'
 async function run(task:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await task();await refresh();setNotice(message)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 function changeLink(provider:PaymentProvider,url:string){setLinks(current=>{const others=current.filter(l=>l.provider!==provider);return url.trim()?[...others,{provider,url}]:others})}
 async function save(event:FormEvent){event.preventDefault();await run(()=>savePaymentSettings(business.id,links,instructions),'Payment options saved. New invoices will copy these options; existing invoices keep their original settings.')}
 return <div className="page-stack settings-page"><div className="page-heading"><p className="eyebrow">Your workspace</p><h1>Settings & plan</h1><p className="quiet">Control how customers see your business and pay you.</p></div>
 {error&&<p role="alert" className="banner error-text">{error}</p>}{notice&&<p role="status" className="banner success-text">{notice}</p>}
 <section className="detail-card"><div className="split-heading"><div><p className="eyebrow">{pro?'Pro':'Free Basic'}</p><h2>A useful free plan. Clear limits.</h2></div><span className="role-pill">{workspace.plan.plan.toUpperCase()}</span></div>
 <div className="usage-grid"><div><strong>{workspace.plan.documents_used} / {workspace.plan.documents_limit}</strong><span>New invoices, estimates & change orders this month</span><progress max={workspace.plan.documents_limit} value={workspace.plan.documents_used}/></div><div><strong>{workspace.plan.customers_used} / {workspace.plan.customers_limit}</strong><span>Stored customers, including archived</span></div><div><strong>{workspace.plan.stored_documents} / {workspace.plan.stored_limit}</strong><span>Stored documents</span></div></div>
 <p className="quiet">Monthly counters reset {workspace.plan.period_end} (UTC). Converting an estimate creates one invoice. Editing, printing, and downloading do not use additional document credits. Deleting a draft does not restore a monthly credit. Existing records are never automatically deleted. Additional lists (jobs, appointments, reminders and messages) are capped at 1,000 stored rows each on Free and 20,000 on Pro. This release supports U.S. dollars.</p>
 <details><summary>Compare Free Basic and Pro</summary><div className="plan-compare"><div><h3>Free Basic</h3><p>1 workspace / 1 user • 100 new documents/month • 250 customers • 1,000 stored documents • payment links • manual payment tracking • print/save PDF • downloaded HTML documents • JSON data export.</p><p>No AI, recorded voice processing, in-app email sending, SMS, or image uploads. Send downloaded documents using your own email or messaging service.</p></div><div><h3>Pro</h3><p>1 workspace / up to 5 members • 1,000 new documents/month • 5,000 customers • 20,000 stored documents • one compressed logo/photo up to 128 KiB • 50 AI requests and 50 voice transcriptions/month • 250 email-send attempts/month.</p><p>Pro access is activated only by the server after an approved subscription or trial. Self-service paid checkout is not enabled in this build. No automatic overage charges.</p></div></div></details>
 {pro&&<p>Usage: {workspace.plan.ai_used}/{workspace.plan.ai_limit} AI requests; {workspace.plan.voice_used}/{workspace.plan.voice_limit} voice transcriptions; {workspace.plan.email_used}/{workspace.plan.email_limit} email attempts.</p>}
 </section>
 <section className="detail-card"><h2>Business identity</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();run(()=>saveProfile(business.id,profile),'Business profile saved.')}}>
 {(['name','email','phone','address_line1','city','state','postal_code'] as const).map(key=><label key={key}>{({name:'Business name',email:'Business email',phone:'Phone',address_line1:'Street address',city:'City',state:'State',postal_code:'ZIP / postal code'})[key]}<input type={key==='email'?'email':'text'} value={profile[key]||''} onChange={e=>setProfile({...profile,[key]:e.target.value})} required={key==='name'} maxLength={key==='address_line1'?200:120} disabled={!admin||busy}/></label>)}
 <div className="full"><button className="primary-button" disabled={!admin||busy}>Save business profile</button></div></form></section>
 <section className="detail-card"><h2>Get paid your way</h2><p>Paste payment links from accounts owned by your business. Customers pay on the provider’s site or app. Owedly does not collect card numbers or route funds through another business’s account.</p><form className="form-grid" onSubmit={save}>
 {(Object.keys(providerNames) as PaymentProvider[]).map(provider=><label className="full" key={provider}>{providerNames[provider]} payment link<input type="url" placeholder={({stripe:'https://buy.stripe.com/your-link',venmo:'https://venmo.com/your-business',paypal:'https://paypal.me/your-business',square:'https://square.link/u/your-link',cashapp:'https://cash.app/$yourbusiness'})[provider]} value={links.find(l=>l.provider===provider)?.url||''} onChange={e=>changeLink(provider,e.target.value)} maxLength={1000} disabled={!admin||busy}/></label>)}
 <label className="full">Other payment instructions<textarea value={instructions} maxLength={2000} onChange={e=>setInstructions(e.target.value)} disabled={!admin||busy} placeholder="For check, cash, bank transfer or Zelle, contact us using the business details above. Do not include passwords or card details."/></label>
 <div className="full banner warning">Use a Venmo business profile and business-appropriate provider accounts. Provider fees and eligibility still apply. Confirm the payee, amount, currency, and invoice number before paying. These links do not automatically mark invoices paid.</div>
 <div className="full"><button className="primary-button" disabled={!admin||busy}>Save payment options</button></div></form></section>
 <section className="detail-card"><h2>Your logo or company photo <span className="role-pill">Pro</span></h2>{workspace.logo&&<img className="brand-preview" src={workspace.logo} alt={`${workspace.profile.name} logo`}/>}
 <p>Shown on invoice and estimate previews, customer-facing printouts, downloads, and Pro invoice emails. One image replaces the previous image. Photos are resized and re-encoded to remove embedded metadata.</p>
 {pro?<><label className="upload-label">Choose PNG, JPG, or WebP (input up to 5 MB)<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!admin||busy} onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>saveLogo(business.id,await prepareLogo(file)),'Branding saved.');e.target.value=''}}/></label>{workspace.logo&&<button className="text-button" disabled={!admin||busy} onClick={()=>run(()=>saveLogo(business.id,null),'Logo removed.')}>Remove logo</button>}</>:<p className="banner">Free Basic uses a clean Owedly document layout without image uploads.</p>}</section>
 <section className="detail-card"><h2>Your data stays portable</h2><p>Download your workspace records as JSON. Export is available on both plans, including when a creation limit is reached. Keep the downloaded file secure; it includes customer and business information.</p><button className="secondary-button" disabled={!admin||busy} onClick={()=>run(()=>exportWorkspace(business.id),'Data export downloaded. Keep it in a secure location.')}>Export workspace records</button><p className="quiet">Owner/admin access is required to change business settings or export the complete workspace.</p></section></div>
}
